const express = require("express");
const dotenv = require("dotenv");
dotenv.config();
const connectDB = require("./config/db");
const authRoutes = require("./routes/authRoutes");
const sensorRoutes = require("./routes/sensor.routes");
const alertRoutes = require("./routes/alert.routes");
const { startSeedJob } = require("./jobs/dataSeed.job");
connectDB();
const app = express();
app.use(express.json());
app.use("/api/auth", authRoutes);
app.use("/api/sensors", sensorRoutes);
app.use("/api/alerts", alertRoutes);
app.get("/", (req, res) => res.send("Backend Running"));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log("Server running on port " + PORT);
  startSeedJob();
});